[package]
name = "chiero-vpp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chiero-span.workspace = true
chiero-model.workspace = true
chiero-check.workspace = true
chiero-recipe.workspace = true
chiero-gcov.workspace = true
chiero-pp.workspace = true
chiero-probe.workspace = true
serde_json.workspace = true
indexmap.workspace = true

[lints]
workspace = true
