[package]
name = "chiero-parse"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chiero-span.workspace = true
chiero-lex.workspace = true
chiero-pp.workspace = true
chiero-ast.workspace = true

[lints]
workspace = true
