[package]
name = "chiero-sema"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chiero-span.workspace = true
chiero-ast.workspace = true
indexmap.workspace = true
smallvec.workspace = true

[dev-dependencies]
chiero-parse.workspace = true
chiero-pp.workspace = true

[lints]
workspace = true
