[package]
name = "chiero-exec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chiero-span.workspace = true
chiero-cir.workspace = true
chiero-mem.workspace = true
chiero-model.workspace = true
chiero-solver.workspace = true
indexmap.workspace = true
smallvec.workspace = true

[lints]
workspace = true
