[package]
name = "chiero-tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chiero-span.workspace = true
chiero-cir.workspace = true
chiero-exec.workspace = true
chiero-check.workspace = true
chiero-opt.workspace = true
chiero-recipe.workspace = true
chiero-select.workspace = true
chiero-gcov.workspace = true
chiero-diff.workspace = true
chiero-vpp.workspace = true
anyhow.workspace = true
indexmap.workspace = true
serde_json.workspace = true

[dev-dependencies]
chiero-pp.workspace = true

[lints]
workspace = true
