[package]
name = "chiero-diff"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chiero-span.workspace = true
chiero-ast.workspace = true
chiero-sema.workspace = true
chiero-parse.workspace = true
chiero-pp.workspace = true
indexmap.workspace = true
serde_json.workspace = true

[dev-dependencies]
chiero-pp.workspace = true
chiero-gcov.workspace = true

[lints]
workspace = true
