[package]
name = "chiero-opt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chiero-span.workspace = true
chiero-cir.workspace = true
chiero-exec.workspace = true
chiero-check.workspace = true
chiero-solver.workspace = true
indexmap.workspace = true

[dev-dependencies]
chiero-lower.workspace = true
chiero-parse.workspace = true
chiero-pp.workspace = true
chiero-sema.workspace = true

[lints]
workspace = true
